nameOverride: tenant-service
replicaCount: 2
config:
  ENVIRONMENT: production
  JWT_ALGORITHM: HS256
externalSecret:
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: /tdse/production/database-url
    - secretKey: JWT_SECRET_KEY
      remoteRef:
        key: /tdse/production/jwt-secret-key
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
