apiVersion: v1
kind: Service
metadata:
  name: {{ include "tdse-service.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "tdse-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "tdse-service.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
