apiVersion: v1
kind: ConfigMap
metadata:
  name: tdse-config
  namespace: tdse
data:
  ENVIRONMENT: "production"
  JWT_ALGORITHM: "HS256"
  AWS_REGION: "us-east-1"
  S3_BUCKET_NAME: "tdse-images-prod"
  DYNAMODB_TABLE_NAME: "inference-results"
  KAFKA_BOOTSTRAP_SERVERS: "b-1.tdse-msk.example:9092,b-2.tdse-msk.example:9092"
  KAFKA_TOPIC_IMAGE_UPLOADED: "image-uploaded"
  KAFKA_TOPIC_IMAGE_PREPROCESSED: "image-preprocessed"
  MODEL_PATH: "/app/models/emotion_model.pt"
  DEVICE: "cuda"
  USE_DUMMY_MODEL_IF_MISSING: "false"
  CREATE_DB_TABLES_ON_STARTUP: "false"
