apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdse-model-pvc
  namespace: tdse
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: efs-sc
